### ISSUE TITLE
Formatting anonymous functions

### ISSUE THREAD

**Issue by Octogonapus** [julia-vscode/DocumentFormat.jl#108]
`x -> foo` is formatted as `x->foo`. I read through Julia's documentation for anonymous functions and it is inconsistent with whether it puts spaces around the arrow. I would rather the formatter ensure there are spaces (i.e., `x -> foo`).

**Comment by davidanthoff** [comment]
Yes, that seems reasonable to me.

**Comment by Octogonapus** [comment]
I am happy to work on this if you point me in the right direction.

**Comment by davidanthoff** [comment]
@ZacLN, can you help?

**Comment by ZacLN** [comment]
Yep this looks to need fixing - thanks for offering to help. This looks to be because the anonymous function operator `->` shares the [precedence level](https://github.com/julia-vscode/CSTParser.jl/blob/master/src/spec.jl#L27) (14) with the type declaration operator `::` (at least within CSTParser's handdling) and each needs to be treated differently by the formatter. 

https://github.com/julia-vscode/DocumentFormat.jl/blob/master/src/passes.jl#L3 is the section of code that determines whether an operator should have single or no spaces around it. Whats needed is a check against the `.kind` of the operator - in the code above it would be `x.args[2].kind !== CSTParser.Tokens.ANON_FUNC`
